### ISSUE TITLE
Exception when handling a streaming request with compression and last-seen

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/ztreamy#25]
```
Uncaught exception GET /.../stream?last-seen=9c53cafa-feb0-41e9-ad9... (X.X.X.X)                              
    HTTPServerRequest(protocol='http', host='XXXXXXXXXXXXXX:XXXX', method='GET', uri='/.../stream?last-seen=9c53cafa-feb0-41e9-ad9...', version='HTTP/1.1', remote_ip='X.X.X.X', headers={'Host': '...', 'User-Agent': 'Jersey/2.19 (HttpUrlConnection 1.7.0_79)', 'Connection': 'keep-alive', 'Accept': 'application/x-ldjson', 'Accept-Encoding': 'deflate'})                                                                          
    Traceback (most recent call last):                                          
      File "ztreamy-server/venv/local/lib/python2.7/site-packages/tornado/web.py", line 1369, in _stack_context_handle_exception                      
        raise_exc_info((type, value, traceback))                                
      File "ztreamy-server/venv/local/lib/python2.7/site-packages/tornado/web.py", line 1572, in wrapper                                              
        result = method(self, *args, **kwargs)                                  
      File "ztreamy-server/venv/local/lib/python2.7/site-packages/ztreamy/server.py", line 909, in get
        non_blocking=False)
      File "ztreamy-server/venv/local/lib/python2.7/site-packages/ztreamy/server.py", line 594, in register_client
        client.send_initial_events(past_data)
      File "ztreamy-server/venv/local/lib/python2.7/site-packages/ztreamy/server.py", line 511, in send_initial_events
        self.send(data)
      File "ztreamy-server/venv/local/lib/python2.7/site-packages/ztreamy/server.py", line 499, in send
        self.callback(data)
      File "ztreamy-server/venv/local/lib/python2.7/site-packages/ztreamy/server.py", line 925, in _on_new_data
        self.write(data)
      File "ztreamy-server/venv/local/lib/python2.7/site-packages/tornado/web.py", line 695, in write
        raise TypeError(message)
    TypeError: write() only accepts bytes, unicode, and dict objects
```

**Comment by jfisteus** [comment]
I've identified two errors related to this issue at `dispatchers.py`. It happens when zlib clients receive use the last-seen feature. I'll upload a fix in a couple of days.
