### ISSUE TITLE
Test  `server._RecentEventsBuffer` exhaustively

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/ztreamy#4]
Sometimes it tries to remove an event that does not exist in the cache of events:

```
Error in periodic callback
    Traceback (most recent call last):
      File "/home/jaf/investigacion/2011_event_streaming/venv-2.7/local/lib/python2.7/site-packages/tornado/ioloop.py", line 502, in _run
        self.callback()
      File "/home/jaf/investigacion/2011_event_streaming/git/ztreamy/server.py", line 379, in _dump_buffer
        self.dispatcher.dispatch(self._event_buffer)
      File "/home/jaf/investigacion/2011_event_streaming/git/ztreamy/server.py", line 646, in dispatch
        self.recent_events.append_events(evs)
      File "/home/jaf/investigacion/2011_event_streaming/git/ztreamy/server.py", line 904, in append_events
        self._append_internal(events[:first_block])
      File "/home/jaf/investigacion/2011_event_streaming/git/ztreamy/server.py", line 939, in _append_internal
        self._remove_from_dict(self.position, len(events))
      File "/home/jaf/investigacion/2011_event_streaming/git/ztreamy/server.py", line 948, in _remove_from_dict
        del self.events[self.buffer[i].event_id]
    KeyError: '1a151adc-eae0-4ff7-98bf-d0920b158486'
```

**Comment by jfisteus** [comment]
Happens it perhaps with event objects that somewhat change their event_id attribute. They shouldn't, but a bug might provoke that.

**Comment by jfisteus** [comment]
Closing it because of being irreproducible.
